### ISSUE TITLE
Certificate printing doesn't work.

### ISSUE THREAD

**Issue by VilleHamunen** [kartoza/projecta#1458] opened 2024-04-18 09:57 UTC
Hello, I'm trying to print a certificate for a course participant in Gispo Oy organization page. I received an error message when trying to print or download the certificates, file and folder doesn't download. The issue is now with all the created courses/platforms, past and upcoming by the dates...

Print certificate pops a new page but gives: error, failed to download PDF file. Same when trying to download the zipped folder, doesn't start downloading. Where the issue might be?

**Comment by Xpirix** [comment] 2024-04-18 10:28
Dear @VilleHamunen,

Thank you for bringing this issue to our attention. We want to let you know that we are currently investigating it and will keep you updated on any progress.

Best regards.

**Comment by Xpirix** [comment] 2024-04-18 13:01
Dear @VilleHamunen,

I think this issue was caused by the disk space available on the server. I successfully printed and downloaded certificates after cleaning the server's disk space. The issue should be fixed now.

Thank you for your patience.

**Comment by VilleHamunen** [comment] 2024-04-19 07:26
Now the printing works, thank you for a quick response!

**Closed as completed** 2024-09-13 07:22 UTC
